language: go
cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg/mod
    - $GOPATH/src/github.com/ltcsuite
    - $GOPATH/src/github.com/golang
    - $GOPATH/src/gopkg.in/alecthomas
go:
  - "1.11.x"
sudo: false
install:
  - export PATH=$PATH:$PWD/linux-amd64/
  - mkdir -p $GOPATH/src/github.com/ltcsuite/
  - go get -d github.com/ltcsuite/ltcd
  - pushd $GOPATH/src/github.com/ltcsuite/ltcd
  - $GOPATH/src/github.com/lightninglabs/neutrino/ltcd_checkout.sh
  - go install . ./cmd/...
  - popd
env:
  matrix:
    - RACE=false
    - RACE=true
script:
  - export GO111MODULE=on
  - export PATH=$PATH:$HOME/gopath/bin
  - ./gotest.sh
